### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by domenkozar** [testing-cabal/testrepository#17]
Would be nice to push a release to pypi to support Python 3.4

**Comment by rbtcollins** [comment]
What about the current release breaks on Python3.4 ?

**Comment by domenkozar** [comment]
```
----------------------------------------------------------------------
Ran 244 tests in 1.674s

FAILED (failures=3, errors=58, skipped=1)

```
Example snippets:
```
======================================================================
ERROR: test_subprocesses_have_stdin (testrepository.tests.test_ui.TestUIContract)
testrepository.tests.test_ui.TestUIContract.test_subprocesses_have_stdin
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/tmp/nix-build-python3.4-testrepository-0.0.20.drv-0/testrepository-0.0.20/testrepository/tests/test_ui.py", line 219, in test_subprocesses_have_stdin
    ui = self.ui_factory()
AttributeError: 'TestUIContract' object has no attribute 'ui_factory'


======================================================================
ERROR: test_subprocesses_have_stdout (testrepository.tests.test_ui.TestUIContract)
testrepository.tests.test_ui.TestUIContract.test_subprocesses_have_stdout
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/tmp/nix-build-python3.4-testrepository-0.0.20.drv-0/testrepository-0.0.20/testrepository/tests/test_ui.py", line 227, in test_subprocesses_have_stdout
    ui = self.ui_factory()
AttributeError: 'TestUIContract' object has no attribute 'ui_factory'


======================================================================
FAIL: test_open_non_existent (testrepository.tests.test_repository.TestRepositoryContract)
testrepository.tests.test_repository.TestRepositoryContract.test_open_non_existent
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/tmp/nix-build-python3.4-testrepository-0.0.20.drv-0/testrepository-0.0.20/testrepository/tests/test_repository.py", line 203, in test_open_non_existent
    raises(repository.RepositoryNotFound(url)))
  File "/nix/store/1nz865hj75xh3dby4id9j574zcv98ncy-python3.4-testtools-1.4.0/lib/python3.4/site-packages/testtools/testcase.py", line 433, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <class 'AttributeError'> is not a <class 'testrepository.repository.RepositoryNotFound'>
```

**Comment by rbtcollins** [comment]
I'm guessing you ran 'unittest2' or something. testrepository 0.0.20 isn't ready for unittest discovery (master is). I note that INSTALL.txt misses the pytz test dependency, but with that installed the tests should run. There is some skew because the tests have connaisence of meaning with the behaviour of traceback2 // testtools where tracebacks are rendered, but nothing that will stop testrepository functioning correctly.

**Comment by domenkozar** [comment]
Cool, going to run `testr` script for now. Would still be nice to have a release out :)

**Comment by rbtcollins** [comment]
yes, will need to cut one - pending getting some big improvements in at the moment.
