### ISSUE TITLE
multiple test failures in version 0.0.20

### ISSUE THREAD

**Issue by jlec** [testing-cabal/testrepository#18]
```python
======================================================================
FAIL: testrepository.tests.test_repository.TestRepositoryContract.test_get_failing_get_subunit_stream(memory)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/testrepository-0.0.20/work/testrepository-0.0.20-python3_5/testrepository/tests/test_repository.py", line 441, in test_get_failing_get_subunit_stream
    ('stopTestRun',)
  File "/usr/lib64/python3.5/site-packages/testtools/testcase.py", line 350, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/usr/lib64/python3.5/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 991509, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  b'Traceback (most recent call last):\n',
  False,
  'text/x-traceback; charset=""utf8""; language=""python""',
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 993946, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  b'  File "/var/tmp/portage/dev-python/testrepository-0.0.20/work/testrepos'
  b'itory-0.0.20-python3_5/testrepository/tests/test_repository.py", line 10'
  b'7, in failing\n    self.fail("oops")\n',
  False,
  'text/x-traceback; charset=""utf8""; language=""python""',
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 993946, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  b'  File "/usr/lib64/python3.5/site-packages/unittest2/case.py", line 690,'
  b' in fail\n    raise self.failureException(msg)\n',
  False,
  'text/x-traceback; charset=""utf8""; language=""python""',
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 993946, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  b'AssertionError: oops\n',
  True,
  'text/x-traceback; charset=""utf8""; language=""python""',
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 993946, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'fail',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  datetime.datetime(2015, 11, 1, 17, 3, 14, 993946, tzinfo=<subunit.iso8601.Utc object at 0x7fd06c0bbb00>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  *,
  True,
  *,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'fail',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('stopTestRun',)]
======================================================================
FAIL: testrepository.tests.ui.test_cli.TestCLIUI.test_outputs_results_to_stdout
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/testrepository-0.0.20/work/testrepository-0.0.20-python3_5/testrepository/tests/ui/test_cli.py", line 166, in test_outputs_results_to_stdout
    """, doctest.ELLIPSIS))
  File "/usr/lib64/python3.5/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: Expected:
    ======================================================================
    FAIL: testrepository.tests.ui.test_cli.Case.method
    ----------------------------------------------------------------------
    ...Traceback (most recent call last):...
      File "...test_cli.py", line ..., in method
        self.fail('quux')...
    AssertionError: quux...
Got:
    ======================================================================
    FAIL: testrepository.tests.ui.test_cli.TestCLIUI.test_outputs_results_to_stdout.<locals>.Case.method
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/var/tmp/portage/dev-python/testrepository-0.0.20/work/testrepository-0.0.20-python3_5/testrepository/tests/ui/test_cli.py", line 152, in method
        self.fail('quux')
      File "/usr/lib64/python3.5/site-packages/unittest2/case.py", line 690, in fail
        raise self.failureException(msg)
    AssertionError: quux
    Ran 1 tests in 0.005s
    FAILED (id=None, failures=1)
Ran 344 tests in 1.617s
FAILED (id=0, failures=2, skips=2)
```
all python verison from 2.7-3.5

**Comment by rbtcollins** [comment]
testtools has connascence of meaning with unittest/unittest2 - somewhat deliberately, but unfortunately it means that changes in unittest necessitate changes in testtools. I believe all these failures are due to that, and subsequently fixed.

**Comment by jlec** [comment]
Correct, d3d6cac4fd42f2067c0dd81be748853f81c348fc fixes the issue
