### ISSUE TITLE
tests fail (0.0.20 and HEAD) with raise mismatch_error

### ISSUE THREAD

**Issue by nieder** [testing-cabal/testrepository#30]
On OS X 10.11, I get these failures with python2.7.  testtools-py is at 2.3.0. The errors are the same for 0.0.20 and HEAD. These are similar to issue #18 but that says it's fixed yet I still see these test errors.
~~~~
======================================================================
FAIL: testrepository.tests.test_repository.TestRepositoryContract.test_get_failing_get_subunit_stream(memory)
tags: worker-3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testrepository/tests/test_repository.py", line 447, in test_get_failing_get_subunit_stream
    ('stopTestRun',)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='inprogress', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 552428, tzinfo=<subunit.iso8601.Utc object at 0x110a03d50>)),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='fail', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 552513, tzinfo=<subunit.iso8601.Utc object at 0x110a03d50>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  *,
  True,
  *,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'fail',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('stopTestRun',)]
======================================================================
FAIL: testrepository.tests.test_repository.TestRepositoryContract.test_get_subunit_from_test_run(memory)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testrepository/tests/test_repository.py", line 493, in test_get_subunit_from_test_run
    ('stopTestRun',)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='inprogress', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 563392, tzinfo=<subunit.iso8601.Utc object at 0x105084d50>)),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='success', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 565528, tzinfo=<subunit.iso8601.Utc object at 0x105084d50>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'success',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('stopTestRun',)]
======================================================================
FAIL: testrepository.tests.test_repository.TestRepositoryContract.test_get_failing_get_subunit_stream(file)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testrepository/tests/test_repository.py", line 447, in test_get_failing_get_subunit_stream
    ('stopTestRun',)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='inprogress', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 632295, tzinfo=<subunit.iso8601.Utc object at 0x10ab18d50>)),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='fail', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 44, 632345, tzinfo=<subunit.iso8601.Utc object at 0x10ab18d50>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  None,
  None,
  True,
  'traceback',
  *,
  True,
  *,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'fail',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('stopTestRun',)]
======================================================================
FAIL: testrepository.tests.commands.test_failing.TestCommand.test_with_subunit_shows_subunit_stream
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testrepository/tests/commands/test_failing.py", line 99, in test_with_subunit_shows_subunit_stream
    ('stopTestRun',)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 _Event(name='status', test_id=u'failing', test_status='inprogress', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 45, 152059, tzinfo=<subunit.iso8601.Utc object at 0x10ab18d50>)),
 _Event(name='status', test_id=u'failing', test_status='fail', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 45, 152098, tzinfo=<subunit.iso8601.Utc object at 0x10ab18d50>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'failing',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status', 'failing', 'fail', None, True, None, None, False, None, None, *),
 ('stopTestRun',)]
======================================================================
FAIL: testrepository.tests.test_repository.TestRepositoryContract.test_get_subunit_from_test_run(file)
tags: worker-3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testrepository/tests/test_repository.py", line 493, in test_get_subunit_from_test_run
    ('stopTestRun',)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/sw/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [('startTestRun',),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='inprogress', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 45, 131346, tzinfo=<subunit.iso8601.Utc object at 0x110a03d50>)),
 _Event(name='status', test_id=u'testrepository.tests.test_repository.Case.method', test_status='success', test_tags=None, runnable=True, file_name=None, file_bytes=None, eof=False, mime_type=None, route_code=None, timestamp=datetime.datetime(2017, 7, 30, 1, 33, 45, 136426, tzinfo=<subunit.iso8601.Utc object at 0x110a03d50>)),
 ('stopTestRun',)]
actual    = [('startTestRun',),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'inprogress',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('status',
  'testrepository.tests.test_repository.Case.method',
  'success',
  None,
  True,
  None,
  None,
  False,
  None,
  None,
  *),
 ('stopTestRun',)]
Ran 345 tests in 1.946s
FAILED (id=0, failures=5, skips=2)
~~~~

**Comment by jelmer** [comment]
This should be fixed in HEAD, and we've now got the CI running on Mac OS confirming that. Please do let us know if you can still reproduce this.

**Comment by nieder** [comment]
Unfortunately, my system is stuck on setuptools v59.6, and I get some different failures because of that. Probably stuck on that version for some time, so best to close this and can revisit if/when possible. thanks.
